name: Azure App Service Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with: 
          ruby-version: 2.6
          
      - name: Install dependencies
        run: bundle install
        working-directory: ./docs
        
      - name: Jekyll build
        run: jekyll build
        working-directory: ./docs
        
      - name: create release dir
        run: mkdir release
        
      - name: Create Zip File
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip release/release.zip -r docs/_site

      - name: list files
        run: ls -R
        
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          # Name of the Azure Web App
          app-name: DocsDemoAppService
          # Enter an existing Slot other than the Production slot
          # slot-name: staging
          # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
          package: ./docs/_site
      
      - name: azure logout
        run: az logout

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_SAND_0AC925B0F }}
          action: "close"
